# Generated by Django 5.0 on 2025-05-17 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('prix', models.IntegerField(default=0, verbose_name='Prix')),
                ('seuil_alert', models.IntegerField(default=0, verbose_name='Alert')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEnterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.typeenterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('addresse', models.CharField(max_length=200)),
                ('idnumber', models.CharField(max_length=50)),
                ('adminMagsin', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs')),
                ('entrepriseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('1', 'Vente'), ('2', 'Location')], max_length=20)),
                ('lieu', models.CharField(max_length=100, verbose_name='Lieu')),
                ('datecreated', models.DateTimeField(auto_now=True)),
                ('raison', models.TextField(verbose_name='Raison')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.product')),
            ],
        ),
        migrations.CreateModel(
            name='MagasinProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magasinId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.magasin')),
                ('produitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.product')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_location', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs')),
                ('magasinId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.magasin')),
                ('produit_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.product')),
            ],
        ),
    ]
